/*
Kogge stone scan
0 1 2 3 4 5
=>
each element = sum of currnet plus prev elements
*/

/*
limit N < 1024 x 1024

*/

#include <iostream>
#include <cuda_runtime.h>
#include <vector>
#include <cmath>

#define BLOCK_DIM 1024

__global__ void segmented_scan_kernel(float* input_d, float* output_d ,float* partials_sums_d,int N, int blocks){

    int i = blockDim.x * blockIdx.x + threadIdx.x;

    /* store to shared memory*/
    __shared__ float block_s[BLOCK_DIM];

    if(i<N) output_d[i] = input_d[i];
    __syncthreads();

    if(i < N){
        block_s[threadIdx.x] = input_d[i];
    }else{
        block_s[threadIdx.x] = 0.0f;
    }
    __syncthreads();

    for(int stride= 1; stride < BLOCK_DIM ; stride*=2){
        if( threadIdx.x >= stride && i < N ){
            block_s[ threadIdx.x ] +=  block_s[ threadIdx.x - stride] ;
        }
        __syncthreads();
    }

    if (threadIdx.x == blockDim.x - 1 && i < N)
    partials_sums_d[blockIdx.x] = block_s[threadIdx.x];
    __syncthreads();

    if (i<N) output_d[i] = block_s[threadIdx.x];
}


__global__ void stitch_scan(float* input, float* scan_of_partial_sums_d, int N, const int blocks){
    int i = blockDim.x * blockIdx.x + threadIdx.x;

    __shared__ float to_add;
    
    if(threadIdx.x ==0 && blockIdx.x ==0){
        to_add= 0.0f;
    }else if(threadIdx.x ==0 && blockIdx.x >0){
        to_add= scan_of_partial_sums_d[blockIdx.x -1];
    }
    __syncthreads();

    if(i < N){
        input[i]+= to_add ;
    }

}


void gpu_scan(float* input, float* output ,int N){
    int threads_per_block = BLOCK_DIM;
    int blocks_per_grid = (N+threads_per_block-1)/threads_per_block;

    float* partials_sums_d;
    float* input_d;
    float* output_d;
    float* scan_of_partial_sums_d;
    float* total_sum;

    cudaMalloc((void**)&partials_sums_d,blocks_per_grid*sizeof(float));
    cudaMalloc((void**)&input_d,N*sizeof(float));
    cudaMalloc((void**)&output_d,N*sizeof(float));
    cudaMalloc((void**)&scan_of_partial_sums_d,blocks_per_grid* sizeof(float));
    cudaMalloc((void**)&total_sum,sizeof(float));


    cudaMemcpy(input_d, input, N*sizeof(float), cudaMemcpyHostToDevice);

    segmented_scan_kernel<<<blocks_per_grid,threads_per_block>>>(input_d,output_d,partials_sums_d, N, blocks_per_grid);
    cudaDeviceSynchronize();
    
    segmented_scan_kernel<<< 1, blocks_per_grid>>>(partials_sums_d,scan_of_partial_sums_d,total_sum, blocks_per_grid, 1);
    cudaDeviceSynchronize();

    stitch_scan <<<blocks_per_grid,threads_per_block>>>(output_d,scan_of_partial_sums_d, N ,blocks_per_grid);
    cudaDeviceSynchronize();

    cudaMemcpy(output, output_d, N*sizeof(float), cudaMemcpyDeviceToHost);

    cudaFree(partials_sums_d);
    cudaFree(input_d);
    cudaFree(output_d);
    cudaFree(scan_of_partial_sums_d);


}

void cpu_scan(const std::vector<float>& input, std::vector<float>& output) {
    output[0] = input[0];
    for (int i = 1; i < input.size(); i++) {
        output[i] = output[i-1] + input[i];
    }
}

/*
Driver code generated by chatGPT
*/
int main() {
    int N = 1026;  

    float* output = (float*) malloc(N*sizeof(float));

    std::vector<float> input(N);
    std::vector<float> cpu_output(N);
    std::vector<float> gpu_output(N);

    // initialize input
    for (int i = 0; i < N; i++) {
        input[i] = i + 1;   // [1,2,3,...]
    }

    // CPU reference
    cpu_scan(input, cpu_output);

    // GPU call
    gpu_scan(input.data(), output, N);
    std::copy(output, output + N, gpu_output.begin());

    // print results
    std::cout << "Input:       ";
    for (auto v : input) std::cout << v << " ";
    std::cout << "\n";

    std::cout << "CPU Scan:    ";
    for (auto v : cpu_output) std::cout << v << " ";
    std::cout << "\n";

    std::cout << "GPU Scan:    ";
    for (auto v : gpu_output) std::cout << v << " ";
    std::cout << "\n";

    // validation
    bool correct = true;
    for (int i = 0; i < N; i++) {
        if (fabs(cpu_output[i] - gpu_output[i]) > 1e-5) {
            correct = false;
            std::cout << "Mismatch at " << i 
                      << " CPU=" << cpu_output[i] 
                      << " GPU=" << gpu_output[i] << "\n";
        }
    }

    if (correct) {
        std::cout << "✅ Scan is CORRECT\n";
    } else {
        std::cout << "❌ Scan is WRONG\n";
    }

    free(output);

    return 0;
}